services:
  immencity:
    container_name: century-immencity
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    volumes:
      - ./public:/app/public

    environment:
      NODE_ENV: production
      PORT: 2973
      HOSTNAME: 0.0.0.0

    ports:
      - "2973:2973"

    restart: unless-stopped